### ISSUE TITLE
실시간 협업 에디터 구현 관련 레퍼런스 

### ISSUE THREAD

**Issue by hataerin** [bbzzkk/LiveMD#10]
[실시간 문서 협업은 어떻게 동작할까](http://www.secmem.org/blog/2019/01/09/operational-transform/)
[ShareJS](http://sharejs.org/) : 여러명의 사용자가 웹브라우저에서 하나의 문서를 실시간으로 동시에 편집 할 수 있는 애플리케이션을 쉽게 구축할 수 있도록 돕는 노드 모듈 (EtherPad)

더 찾으면 추가할게용!

**Comment by Joylish** [comment]
ShareJS, YJS 좋은 라이브러리가 많네요 ㅎㅎ express로 어느 기능까지 지원하는지 한번 구현해보면서 알아봐야할거같네요 감사합니다!

**Comment by JSWww** [comment]
올려주신 링크 확인해보겠습니다

**Comment by soyoung-Jung** [comment]
감사합니당

**Comment by kwak-bs** [comment]
좋아용ㅎㅎ
