### ISSUE TITLE
회원가입 및 로그인 플로우 차트 및 기술셋 조사

### ISSUE THREAD

**Issue by JSWww** [bbzzkk/LiveMD#11]
# 회원가입 및 로그인 플로우 차트 및 기술셋 조사

### 이슈 ❗️

회원가입 및 로그인 플로우 차트를 그려보았습니다!

![플로우](https://user-images.githubusercontent.com/9590693/94921170-b29a8580-04f2-11eb-883f-e3776860cca7.png)

다음은 기술셋 정리 링크입니다

### [TIL - Optimistic Replication(낙관적 복제)](https://github.com/bbzzkk/TIL/blob/jswww/201002-Optimistic_Replication.md)

# 나의 의견 😎

위의 플로우 차트는 회원가입 및 로그인 할 때의 큰 틀이고 각 처리에서 user story를 생각해보면 될 것 같습니다!

# 관련된 이슈 📎

#4 

# 레퍼런스 📚

> 관련 레퍼런스 없음

**Comment by soyoung-Jung** [comment]
그러면 구글 로그인과 일반 회원가입이 같이 되는 거군요! 그리고 엄청나게 상세한 조사를 하셨군요..! 수고하셨어요 이따 회의에서 다시 나누어보아요~!

**Comment by Joylish** [comment]
플로우차트 그리신다구 고생하셨습니다! 수요일 오프라인 회의때 하나로 합쳐봐요 ㅎㅎ!

**Comment by kwak-bs** [comment]
큰 그림으로 잘 잡혀 있는거 같아요 수고하셨습니다!

**Comment by hataerin** [comment]
확인했습니다!
