### ISSUE TITLE
LiveMD를 위한 기술 조사

### ISSUE THREAD

**Issue by soyoung-Jung** [bbzzkk/LiveMD#12]
# LiveMD를 위한 기술 조사

### Websocket API

서버와 클라이언트 간에 Socket Connection을 유지해서 언제든 양방향 통신 또는 데이터 전송이 가능하도록 하는 기술. 즉, 실시간 기능 구현을 위한 기술.

- 참조

[Springboot와 websocket을 이용하여 채팅 앱 구현하기](https://ratseno.tistory.com/71?category=773803)

***

### 일관성 관리 및 동시성 제어를 위한 기술

여러 클라이언트에서 보낸 메세지의 변경사항을 머지하는 두가지 알고리즘.

#### 1. Operational Transform

operations를 바꿈으로써 일관성 관리를 한다.

다수의 클라이언트(문서를 수정하는 역할) + 하나의 서버(수정한 내용을 동기화)

- 참조

http://www.secmem.org/blog/2019/01/09/operational-transform/ 

#### 2. CRDTs

state를 바꿈으로써 일관성 관리를 한다. OT보다 더 쉽다.(?)

- OT vs. CRDTs

  https://velog.io/@diane_at_work/%EA%B3%B5%EB%8F%99%ED%8E%B8%EC%A7%91-editor%EC%84%A0%EC%A0%95-t3k5z2wvoh

**Comment by hataerin** [comment]
확인했습니다!

**Comment by JSWww** [comment]
확인했습니다!

**Comment by Joylish** [comment]
데이터 동기화를 위해서 real time collaborative 관련 알고리즘 연구가 다양하게 진행되어왔네요! real time 라이브러리가 어떤 이론을 바탕으로 만들어졌는지 알 수 있는 기회네요 ㅎㅎ좋은 정보 감사합니다~

**Comment by kwak-bs** [comment]
감사합니다!
