### ISSUE TITLE
실시간 문서 작성 및 프리뷰 기술 조사

### ISSUE THREAD

**Issue by Joylish** [bbzzkk/LiveMD#13]
# 실시간 문서 작성 및 프리뷰 기술 조사
이슈 ❗️
실시간 문서 작성 및 프리뷰에 필요한 기술로 조사해 보았습니다.

# 나의 의견 😎
### 1. lucy-xss-filter: xss attack 대비하기
(client에서 markdown api를 사용한다고 가정했습니다.)
client에서 마크다운 문법으로 작성된 글을 html로 변환해서 server에 넘겨줍니다. server에서 html형 데이터를 html entity로 변환하여 db에 저장합니다.
client에서 해당 데이터를 요청하면, 서버에서 db에서 해당 html entity 데이터를 불러 html형식으로 변환하여 client에 넘겨줍니다.

### 2. documentDB/nosql
문서 전용 데이터베이스로 AWS에서 서비스되고 있습니다. XML, JSON과 같은 DOCUMENT를 이용해 레코드를 저장합니다. 테이블의 스키마가 유동적으로 레코드마다 각각 다른 스키마를 가질 수 있어 트리형 구조로 레코드를 저장하거나 검색하는 데 용이합니다. 

### 3. 화상채팅
WebRTC API + Socket.io

# 관련된 이슈 📎
#4 

# 레퍼런스 📚
[xss공격](https://4rgos.tistory.com/1)
[lucy-xss-filter](https://www.leafcats.com/52)
[document DB](https://www.44bits.io/ko/post/news--aws-announce-mongodb-compatible-documentdb)
[무중단배포](https://jojoldu.tistory.com/267)
[etherpad docker 이미지](https://hub.docker.com/r/etherpad/etherpad) 
[웹브라우저 화상채팅](https://velog.io/@ehdrms2034/WebRTC-%EC%9B%B9%EB%B8%8C%EB%9D%BC%EC%9A%B0%EC%A0%80%EB%A1%9C-%ED%99%94%EC%83%81-%EC%B1%84%ED%8C%85%EC%9D%84-%EB%A7%8C%EB%93%A4-%EC%88%98-%EC%9E%88%EB%8B%A4%EA%B3%A0)
[WebRTC 화상채팅](https://forest71.tistory.com/211)

**Comment by hataerin** [comment]
확인했습니다!!

**Comment by soyoung-Jung** [comment]
확인했습니다 ~!

**Comment by JSWww** [comment]
레퍼런스 링크 확인해보겠습니다~!

**Comment by kwak-bs** [comment]
감사합니다~~
