### ISSUE TITLE
2020.10.02 오후 MEETING

### ISSUE THREAD

**Issue by JSWww** [bbzzkk/LiveMD#14]
# 2020.10.02 오후 MEETING

## MEETING 목적 🚩

- [x] 기술 스택 조사, flowchart 만들어 온 것에 대해 회의 및 토론
- [x] 기획서 목차 초안 작성 및 역할 분담

## MEETING 내용 ✍️

연주 : 
- 프론트엔드에서 editor 구현하기 위해서 사용할 api 정해주세요.
- 깃허브에 meeting, discussion 등에 이슈를 올릴 때 쓰는 템플릿을 LiveMD 사용자도 자기가 저장한 템플릿을 불러와서 쓸 수 있다면 좋지 않을까 생각을 했습니다.
 
성원 :
- CRDT에 대해 각자 알아오기.

병선 : 
- 채팅창은 플로팅 형식으로 만들면 좋을 듯 합니다.

#### 목차

- **서비스 개요 (비즈니스 포커스) - 소영, 병선**
    - 기획 배경 : 회의하다보니 협업 에디터와 화상회의 왔다 갔다 너무 불편
    - 기획 목적 : 실시간 협업 에디터와 화상 회의 합쳐 보자
    - 기획 효과 : 다양한 채널을 사용할 필요 X
    - 시장 조사 : 현재 존재하는 서비스 분석
        - HackMD
        - Typora
        - Google Meet
    - 문제점(문제 상황), 타겟 정의
    - 문제점 해결 : 우리는 무엇(어떤 니즈)을 해결할 수 있다
    - 우리 서비스와의 비교 표

- **주요 서비스 (기술 && 기능 포커스) - 연주, 성원**
    - 메인화면 설계
    - 실시간 협업 문서 작업 서비스
       - CRDT 기술 적용(적용 기술)
    - 실시간 화상 채팅 서비스
       - Web RTC

- **서비스 구체화 - 태린**
    - 플로우 차트 통합본
    - 개발조직구성 및 개발 추진 일정
    - 이번 프로젝트로 적용하고 싶은 기술

**Comment by hataerin** [comment]
정리 감사드려영ㅎㅎ

**Comment by soyoung-Jung** [comment]
수고했어요 수욜날 힘내서 보아요~~

**Comment by Joylish** [comment]
real time 협업 프로젝트! 흥미진진하네요 정리감사합니다~

**Comment by kwak-bs** [comment]
정리 감사합니다 ㅎㅎ
