### ISSUE TITLE
2020.10.05 오후 MEETING

### ISSUE THREAD

**Issue by Joylish** [bbzzkk/LiveMD#15]
# 💐 2020.10.05 LiveMD 회의 💐

### 1. 수요일 시간 정하기 
10시 ~ 18시 (늦으면 소주 1잔 더 마시기 ^^^^)

#### 공통
- 플로우 차트 수정하기
- github wiki로 회의 기록 알아내기!

#### Server
- 마이크로서비스 나누기
- 각 서비스 api 문서 작성
- api 문서에 따라 개발

##### 개인별 할 일
- 태린: 실시간 커뮤니케이션 webRTC + express
- 연주: 실시간 협업 yjs + express
- 소영: 회원가입 및 로그인 spring boot

#### Client
- 성원: 마크다운 에디터 오픈소스 기능들 파악해보기
    - toast ui
    - codemirror
    - react md-editor

- 병선 
    - 월 : 로그인/회원가입 기능, 디자인 공부, 기획서 완성~~
    - 화 : 메인화면 기능, 디자인 공부 (hackMD + Apple) 
    - 수 : 마크다운 에디터 구상 공부...? 

#### 1) 기획 제출 및 발표 일정 확인
- 기획서 ppt 제출: 10월 7일, 수요일
- 팀 공통 모듈 구현: 10월 8일, 목요일

**공통 모듈 후보**
    - 팀 레포지토리
    - 문서 관리
    - 회원가입
- 기획서 ppt 발표: 10월 9일, 금요일

#### 2) 기획 ppt 피드백
- [ ] 목차 완성하기
- [ ] Live MD 설명 완성하기
- [ ] 시장 조사 완성하기

다들 고생 많으셨습니다!  2) 기획 ppt 피드백은 화요일, 10월 6일 오전 10시에 만나서 10분여간 진행할 예정입니다

**Comment by kwak-bs** [comment]
감사합니다 ㅎㅎ

**Comment by JSWww** [comment]
확인했습니당!

**Comment by soyoung-Jung** [comment]
수고하셨습니당

**Comment by hataerin** [comment]
확인했습니다!
