### ISSUE TITLE
2020.10.09 멘토링 피드백

### ISSUE THREAD

**Issue by JSWww** [bbzzkk/LiveMD#16]
# 2020.10.09 멘토링 피드백

- 강훈기 멘토님

    - 마크다운 에디터로 한정하는 것이 아니라 에디터를 체인지하여 페어 프로그래밍 쪽이라던지 확장 가능할 것이다. 
    ---

- 박용희 멘토님

    - 기간 안에 서비스들이 잘 구현될까?
    - 개발 환경이 이기종 프로토콜들이 요구될 수도 있고 개발 환경을 미리 고려하고 검증해봐야 한다.
    - 나중에 시연할 때 서비스를 잘 표현할 수 있어야 한다.
   ---

- 한정헌 멘토님

    - 개발 범위가 단기간에 하기에는 클 것이다.
    - 팀 생성이라던지 이러한 부가적인 기능들도 생각보다 오래 걸릴 것이다.
    - 기획서에서 플로우 차트는 정말 옛날 방식이다. 보는 사람 입장에서 잘 안 와닿고 회사에서도 순서도는 잘 안 쓴다.
    - 개발 일정은 워터폴 방식으로 잡아 놓고 프로젝트 진행은 애자일 스크럼으로 한다는 것에서 의미가 맞지 않다.
    - 스프린트라는 개념 자체가 플랫하게 계획을 잡는 것이 아니다. 스프린트를 주 차로 나누고 제일 핵심 기능(제일 기술적으로 검증해야할 기능)을 파일럿 및 프로토 타입을 가져 스프린트 단위로 시연 및 회고를 진행하는 것이 좋다.
    - 계획을 실현 가능하게 ... 제일 먼저 구현해야 할 기능 구현하고 미뤄야할 것은 미뤄야 한다.
    - 프로젝트가 용두사미가 될 수 있다. 약 2주 단위로 스프린트를 진행하는 것을 추천!
    - 기존에 마크다운으로 운영되고 있는 페이지들(github wiki or 개발 블로그)에 퍼블리싱 할 수 있으면 더 파급력 있을 것이다.
    ---

- **최병욱 멘토님**

    - BBB(Big Blue Button, webRTC 관련)라는 화상 관련 오픈소스가 있다.
        - https://bigbluebutton.org/
        - https://docs.bigbluebutton.org/2.2/install.html
    - BBB는 사용자 입장에서 기능이 너무 많아 복잡하다. 우리 프로젝트는 기존에 있는 솔루션들에서 우리가 실제 필요한 것만 간추려 구현할 수 있으면 좋을 것이다.
    - 설정 및 사용을 단순화해서 차별점을 어필할 수 있을 것이다.
    - 개발 일정이 상당히 타이트하다. 개발 일정에 대해 좀 더 구체화할 필요가 있다.
    - webRTC 관련해서 브라우저마다 제약 조건이 많아서 시행착오를 많이 겪을 것이다.
    ---

## 프로젝트 진행 시 고려해야 할 것

- 서비스를 어떻게 쪼갤지를 고민하기보다 기능을 단순화하여 기존의 서비스에서 우리 프로젝트에 필요한 기능들만 추출 하는것이 우선
- 기능을 세분화하고 팀의 담당자 정하기나 세션 유지 등 구체적인 구현에 대해서 더 자세하게 생각하기
- 오픈 소스를 합쳐보기 -> 기존에 존재하는 오픈소스들을 합쳐서 하나의 서비스로 나타내는 것도 어려울 수 있기 때문
- 개발 서버를 따로 구축하여 개발 진행할 수 있게 하고 개발 환경에 대해 고려해 봐야 함
- 개발 일정에 대해 좀 더 구체화할 필요가 있음 -> 스프린트 회의를 이용

## 2020.10.16 까지 멘토님이 요구한 것
- 프로젝트의 메인 기능화면을 보여줄 수 있도록! (메인화면, 로그인 같은 기능은 다 구현해내지 못했더라도)

## 내일 회의 때 TODO
- [x] Jira 써보기

- [x] 1차 스프린트 회의(2020-10-10 오후 9시)
    - 폭포수 -> 애자일 계획 수정하기
        - 핵심기능 먼저
            - 파일럿: 기술검증 먼저 하기 (스프린트1)
            - -> 시연 및 회고 진행 (반복)
            - 스프린트2 진행

- [x] 모듈 프로젝트
    - 로그인은 우선 구글 로그인으로만 구현

- [ ] 화면 설계 기획

- [ ] 요구사항 정의서 기획

**Comment by soyoung-Jung** [comment]
정리 감사합니다.

**Comment by kwak-bs** [comment]
정리 감사합니다 ✌😊😊

**Comment by Joylish** [comment]
멘토링 받는다고 다들 수고많았어요~!! 정리감사합니다 🤓

**Comment by hataerin** [comment]
정리 감사합니당!!

**Comment by kwak-bs** [comment]
다들 정말 고생했어요! 정리 감사합니다 ㅎㅎ
