### ISSUE TITLE
2020.09.24 오후 MEETING

### ISSUE THREAD

**Issue by hataerin** [bbzzkk/LiveMD#2]
# 2020.09.24 오후 MEETING

## MEETING 목적 🚩

- 연휴 계획 세우기
- 개발 조언 구하기

####  강사님 조언

유사 서비스, 기술셋 조사하기

[도메인+커멘드] + 제약사항 + 화면 으로 나눠서 구성해보기

추천 차별점: 에디터는 **편리함**이 핵심! 키보드 이벤트 추가하기

Mybatis vs JPAㄻ

- mybatis 
  - 쿼리 반복적으로 입력해야함
  - 디버깅 편함
- JPA
  - CRUD다 만들어줌
  - 작성 및 디버깅 어려움 -> 기한내에 만들 수 있을지?
  - 쿼리 커스텀 가능하긴 함

## MEETING 결과 📌

- ### 추석 연휴 전에 할 일

  **[9/24(목) ~ 9/27(일)]**

  - TIL 2개 업로드

  - 유사서비스 조사
    - 기술셋 조사하기
  - 기획서 작성 (일욜 저녁 회의시간)

  **[9/28(월) ~ 10/4(일)]**

  - 공통
    - 스토리보드 작성
    - 유저 에픽 작성
    - 기술셋 개념 공부해오기
    - 위키 페이지 작성
    - 이슈 폼 작성
    - **이름 정하기**

  - Front
    - 리액트 공부하기
  - Back
    - Spring boot책 : 1~5장 공부하기
    - MSA 구성 생각하기

**Comment by kwak-bs** [comment]
확인했습니다 감사합니다~!~
