### ISSUE TITLE
모듈 프로젝트 버그 수정 history

### ISSUE THREAD

**Issue by Joylish** [bbzzkk/LiveMD#22]
1차 모듈 프로젝트동안 개발하시면서 겪었던 버그 수정 이력 까먹기 전에 간단히 코멘트로 남기면 좋을 거 같아요!

**Comment by soyoung-Jung** [comment]
오ㅎㅎ 기록할게요
저는 이번에 연주 언니랑 소셜 로그인 부분 개발을 진행했습니다~
여러가지 에러가 있었는데 기억나는대로 일단 코멘트 달게요!
### 첫 번째
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.2.1.RELEASE:run
에러 해결하기 위한 시도했던 방식ㅜ
1) .m2 폴더 삭제
2) mvn clear
3) 프로젝트 다시 생성.. (노가다)
4) jdk버전 바꿔보기

결국 3)번 방법으로 다시 해결되었습니다. 정확한 원인이 무엇인지는 파악하지 못했습니다^^...

### 두번째
build가 안된 경우
mvn spring-boot:run을 했을 때 에러가 났었습니다. 
이유는 directory를 server/spring-social로 바꾸지 않고 했기 때문이었습니다.

### 세번째
port 충돌
spring-boot의 포트 번호 8080 -> 5959로 바꾸려고 시도하였습니다. 하지만, google cloud에서 발급 받은 oauth client의 redirect uri를 붙여보고, 여러 포트 설정을 바꿔보았지만 결국 해결하지 못했습니다. 나중에 더 찾아보겠습니다..ㅎㅎ..ㅠ

**Comment by JSWww** [comment]
프론트
1. 로그아웃 버튼 클릭 시 다시 로그인 버튼이 클릭되는 현상
- 원인: 마우스 클릭 이벤트가 로그인 a 태그까지 적용
- 해결: handleLogout 함수에 e.preventDefault() 코드 추가하여 a 태그의 동작을 중단시킴

2. 메인 페이지 진입 시 무한 루프 발생
- 원인 : useEffect 무한 루프 발생
- 해결 : useEffect 두 번째 인자로 빈 배열 주어 한 번만 렌더링 되게 함
