### ISSUE TITLE
서비스 이름과 차별점을 위한 아이디어 제안

### ISSUE THREAD

**Issue by hataerin** [bbzzkk/LiveMD#3]
# 🤗서비스 이름과 차별점을 논의해보아요🤗
- 우리 서비스의 아이덴티티를 위해 직관적인 이름을 지어봅시다
- 다른 서비스와의 차별점을 생각해 봅시다

#### 유사 서비스 종류!
- Slack
  - 사전적 의미로는 '늘어진', '느슨한' 
  - 바쁜 직장인들이 슬랙을 사용함으로써 여유를 가질 수 있다는 의미를 담고있음
- 행아웃 / 구글 미트
- Hack MD
- ZOOM
- Typora
  - 몬가 타이핑 어쩌고의 느낌스,,,

### 기존 서비스와의 차별점 제안
- 구글미트 + HackMD = 우리 서비스♥
     - 실시간 음성, 채팅 공유기능

### 이름후보
- **Mr.D**
  - 마크다운의 MD스펠링을 이용해 지어봄
- **McDonald's**
  - 마크다운의 MD스펠링을 이용해 지어봄ㅋㅎ
- **Periodt.**
  - 미쿡 핵인싸들의 2020 유행어/신조어 라고 합디다
  - 논쟁할 것도 없고 더 말할 것도 없다, 그만큼 내 말이 맞다, 더 이상 의견은 필요 없다 라는 뜻
  - 우리 서비스 말고 뭘 더 사용해? 말할것도 읎다^^ 이런 느낌으러 지어봄ㅎㅎ
- **헤이회의**
  - 발음을 이용한 언어유희....ㅎ

## 관련된 이슈 📎

> 관련 이슈 없음

## 레퍼런스 📚

> 레퍼런스 없음

**Comment by kwak-bs** [comment]
호오! 되게 신박하게 잘 지으신거 같아요! 그럼 저도 이름 제안해보겠습니다. 
-  ***Together***
     - 함께 한다는 쉽고 간단한 의미! 그리고 멋도 있다고 생각합니다! 약간 ***Brunch***에서 따왔음

-  ***Season***
     - Google은 구골(10의 100제곱)에서 유래했고, kakao는 초콜릿이 주는 달콤함과 모바일 커뮤니케이션이 주는 즐거움이 잘 맞아 떨어져서 이렇게 지었다고 합니다. Naver는 Navigator + -er 을 붙여서 항해하는자? -> 정보의 바다 라는 의미에서 유래했다고 하더군요. 즉, 하고 싶은 말은 굳이 네이밍할 때 깊게 생각할 필요 없다고 생각합니다. ㅎㅎ 그냥 사계절 내내 함께 사용하자는 의미에서 season 해봤어요 ㅎㅎ  

-  ***ihopis***
     - I hope our project is successful.을 줄여봤습니다 ㅎㅎ

**Comment by soyoung-Jung** [comment]
저도 몇가지 제안해볼게요!

- Mark Duo
  마크다운을 사용할 때 언제나 함께하는 듀오라는 뜻에서 MD의 앞글자를 따서 지어봤습니다.

- LiveMD
  라이브로 md를 작성을 공유할 수 있다는 심플한 의미입니다.

**Comment by Joylish** [comment]
* Muuu
* Hey? Hey!
* DEEP MIND

**Comment by JSWww** [comment]
- collaboMD
- TeamD

**Comment by kwak-bs** [comment]
## [추가 기능 제안 ] 
- 채팅, 오디오, 비디오(캠), 음악,
