### ISSUE TITLE
2020.09.28 오후 MEETING

### ISSUE THREAD

**Issue by kwak-bs** [bbzzkk/LiveMD#4]
# 2020.09.28 오후 MEETING

## MEETING 목적 🚩

- [x] 서비스/홈페이지 이름 정하기
- [ ] 기술 스택 알아보기 
- [ ] 기획서 초안 작성하기

### 기획서 목차 (1차 기획안)

- 서비스 개요 
    - 기획 배경
    - 기획 목적
    - 기획 효과 
    - 주요 기능( 차별화된 기능 + 벤치마킹!)
 
- 플로우 차트 
    - 유저 플로우 (로그인 / 비로그인)
    - 로그인 프로세스 

- 화면 설계
    - 메인화면 
    - 로그인 
    - 서비스 페이지

- 계획 수립 
    - 추진 일정 (역할 분담)

### 플로우차트 그려오기
- 병선 : 실시간 소통(음성, 채팅, 영상)
- 성원 : 회원가입 및 로그인
- 연주 : 실시간 문서 작성 및 프리뷰
- 태린 : 팀원초대하기
- 소영 : 마크다운 문서 수정 이력 열람하기

### 과제
- 실시간 에디터 기술스택 조사해서 이슈로 올리기

**Comment by soyoung-Jung** [comment]
고생 많으셨습니다!! 꼭 숙제 해올게요~!~!

**Comment by hataerin** [comment]
수고하셨습니당!!ㅎㅎ

**Comment by Joylish** [comment]
감사합니둥둥

**Comment by JSWww** [comment]
정리 감사합니당
