### ISSUE TITLE
기능 구현 관련 레퍼런스입니다.!!!

### ISSUE THREAD

**Issue by kwak-bs** [bbzzkk/LiveMD#5]
# 관련 레퍼런스

- ReactDocs github
https://github.com/floresfxf/ReactDocs
![ReactDocs1](https://i.imgur.com/xveX4O4.png)
![ReactDocs2](https://i.imgur.com/V5Zy2si.png)

- collab-me
https://github.com/thejameswang/collab-me

![collab-me-detail](https://i.imgur.com/19umQJR.png)
![collab-me-detail2](https://i.imgur.com/AQjVkwa.png)

- Google Docs 같은 실시간 협업 에디터를 만드는 방법
https://hackerwins.github.io/2019-04-16/co-editor

- Making A Simple Real-Time Collaboration App with React, Node, Express, and Yjs
https://medium.com/@ethanryan/making-a-simple-real-time-collaboration-app-with-react-node-express-and-yjs-a261597fdd44

- Realtime Chat app using Kafka, SpringBoot, ReactJS, and WebSockets
https://dev.to/subhransu/realtime-chat-app-using-kafka-springboot-reactjs-and-websockets-lc

**Comment by soyoung-Jung** [comment]
넵 혹시나 더 참고할만한 레퍼런스가 있다면 댓글로 더 추가하는 것도 좋을 것 같습니다~ 감사해요!

**Comment by hataerin** [comment]
정리 감사드려용ㅎㅎㅎ

**Comment by Joylish** [comment]
역시역시~~짱! 감사합니당

**Comment by JSWww** [comment]
확인했습니다~
