### ISSUE TITLE
수정이력 열람 플로우 차트

### ISSUE THREAD

**Issue by soyoung-Jung** [bbzzkk/LiveMD#6]
# 수정이력 열람 플로우 차트

## 이슈 ❗️

수정이력 열람 과정을 플로우 차트로 나타내 보았습니다. 

![image](https://user-images.githubusercontent.com/68037174/94774773-83ecb400-03f9-11eb-82be-aa6e2be9be5e.png)

## 나의 의견 😎

- 수정이력은 다음과 같이 수정날짜/수정시간/수정한 사람을 통해 구분할 수 있습니다.

  ![image](https://user-images.githubusercontent.com/68037174/94774496-fe690400-03f8-11eb-9bed-6d015d8a4e70.png)

- 수정된 이력을 저장하는 방법을 정해야 한다고 생각합니다.

  - 자동 저장

  - save버튼 혹은 `ctrl+s`를 누를 경우

    

## 관련된 이슈 📎

> 관련 이슈 없음

## 레퍼런스 📚

[flowchart editor](https://www.draw.io/)

[기획 과정 참고 블로그](https://brunch.co.kr/@mmmangchi/20)

**Comment by kwak-bs** [comment]
Flowchart 잘 봤습니다. ㅎㅎ 저장 버튼을 누르면 작성 중인 MD 파일을 history로 남길지 선택할 수 있는 것이군요! Back-end 입장에서 봤을때 데이터를 선택적으로 저장할 수 있어서 효율적이라고 생각됩니다.

**Comment by Joylish** [comment]
플로우차트~~~~수요일에 잘합쳐봐영

**Comment by JSWww** [comment]
확인했습니다!!

**Comment by hataerin** [comment]
확인했습니다!!
