### ISSUE TITLE
실시간 소통 플로우 차트 (채팅)

### ISSUE THREAD

**Issue by kwak-bs** [bbzzkk/LiveMD#7]
# 실시간 소통 플로우 차트(chat)

## 이슈 ❗️

실시간 소통(chat) 과정을 플로우 차트로 나타내 보았습니다.

![char flowchart](https://user-images.githubusercontent.com/51367622/94827729-bcb17b00-0443-11eb-8b67-56c1c6cddb25.PNG)

## 나의 의견 😎

- 실시간 소통 방법에는 채팅, 마이크, 비디오 등등.. 다양한 방법이 존재하지만 최우선적으로 구현해야 하는 기능은 채팅이라고 생각하여 채팅에 관한 flowchart를 먼저 작성해보았습니다.
- 클라이언트 부분과 서버쪽 부분으로 나누어서 데이터의 처리 및 동작 방법에 대해 flowchart를 작성해보는것도 방법이라고 생각합니다. 
- 큰 그림 위주로 먼저 flowchart를 작성해보았는데 미흡한 부분이 있으면 피드백 부탁드립니다.!

## 관련된 이슈 📎

> 관련 이슈 없음

## 레퍼런스 📚

[flowchart editor](https://www.draw.io/)

[순서도 작성 방법](http://tcpschool.com/codingmath/flowchart)

**Comment by soyoung-Jung** [comment]
데이터의 처리 및 동작방법은 우선 기술스택에 대해서 먼저 조사를 하고 정립을 하면 좋을 것 같아요. 그리고 채팅창을 닫고 싶을 때 어떤 식으로 하면 좋을지 생각해보는 것도 좋을 것 같습니다~~

**Comment by Joylish** [comment]
오옹 ㅎㅎ 화상채팅 플로우차트를 추가해야겟군여 수요일에 그거랑 합쳐봐용!

**Comment by JSWww** [comment]
확인했습니다~!

**Comment by hataerin** [comment]
확인했습니다!
