### ISSUE TITLE
실시간 문서 작성 및 프리뷰

### ISSUE THREAD

**Issue by Joylish** [bbzzkk/LiveMD#8]
# 실시간 문서 작성 및 프리뷰 플로우 차트(chat)
이슈 ❗️
실시간 문서 작성 및 프리뷰 과정을 플로우 차트로 나타내 보았습니다.
![실시간 문서 작성 및 프리뷰](https://user-images.githubusercontent.com/52230415/94905688-3c892500-04d8-11eb-9c4a-d37763b28129.png)

# 나의 의견 😎
1. 깃허브에 meeting, discussion 등에 이슈를 올릴 때 쓰는 템플릿을 LiveMD 사용자도 자기가 저장한 템플릿을 불러와서 쓸 수 잇다면 좋지 않을까 생각을 했습니다.

# 관련된 이슈 📎
#4 

# 레퍼런스 📚
[플로우 차트 그리는 방법](https://m.blog.naver.com/onlybest01/220080008810)
[collab-me](https://github.com/thejameswang/collab-me)

**Comment by kwak-bs** [comment]
잘 봤습니다 ㅎㅎ 제 글을 복붙하셨군용 ㅎㅎ

**Comment by soyoung-Jung** [comment]
1분간격으로 자동저장되면 마지막에 save버튼을 누르지 않더라도 history만 남지 않을뿐 파일 자체는 저장되는것일까요?

**Comment by Joylish** [comment]
> 1분간격으로 자동저장되면 마지막에 save버튼을 누르지 않더라도 history만 남지 않을뿐 파일 자체는 저장되는것일까요?
네넵 맞습니다 save 누른거만 버전관리 되는 형태로 일단 제안해보았습니다

**Comment by JSWww** [comment]
자세하게 구성하셨네요~ 확인했습니다!

**Comment by hataerin** [comment]
확인했습니다!
