### ISSUE TITLE
팀페이지 플로우 차트

### ISSUE THREAD

**Issue by hataerin** [bbzzkk/LiveMD#9]
# 팀페이지 플로우 차트

## 이슈 ❗️
팀페이지 개설 및 팀원 초대 과정을 플로우 차트로 나타내 보았습니다
![image](https://user-images.githubusercontent.com/26705587/94908388-8c69eb00-04dc-11eb-9b91-19beb6d5f218.png)

## 나의 의견 😎
![image](https://user-images.githubusercontent.com/26705587/94910333-904b3c80-04df-11eb-96e8-d947d77e49ac.png)
- 팀페이지의 주소 url을 직접 설정할 수 있게 하는것도 좋은것 같습니다
- 팀원 초대시 상대방의 초대 수락 여부를 확인할 수 있으면 좋을것 같습니다
- 팀원 초대시 회원/비회원 상관없이 초대할 수 있는지 논의해보기!
- 개인레포에도 다른사람 초대할 수 있을지 논의해보기!

## 관련된 이슈 📎
#4

**Comment by kwak-bs** [comment]
잘 봤습니다. ㅎㅎ 팀원을 꾸릴 때는 로그인 된 사용자만 팀원을 꾸릴 수 있도록하면 좋을 것 같다는 의견을 내봅니다 ㅎㅎ

**Comment by soyoung-Jung** [comment]
저도 회원만 그 팀에 초대할 수 있었으면 좋겠습니다! 만약 회원이 아닌 사람에게 초대 이메일이 가는 경우에는 가입을 할 수 있도록이요!

**Comment by Joylish** [comment]
왘ㅋㅋ영어당! 수요일에 합쳐봐용!

**Comment by JSWww** [comment]
확인했습니다~!
